### ISSUE TITLE
Look into github actions

### ISSUE THREAD

**Issue by scottc943** [aegnx/ramsay.py#7]
https://github.com/marketplace/actions/pyinstaller-action

Look into this so users can download binaries directly from releases. 

```
name: Auto release binaries
on:
  pull or push (you could even use both just look at docs):
    branches:
      - main
concurrency: production

jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Minor version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - name: Setup python env
        uses: actions/something to setup python on the ubuntu node
    

      - name: Create Binary
        uses: something from this - https://github.com/marketplace/actions/pyinstaller-action

      - name: Minor version for each merge
        id: taggerFinal
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.taggerFinal.outputs.new_tag }}
          tag: ${{ steps.taggerFinal.outputs.new_tag }}
          artifacts: "bbm"
          bodyFile: ${{ steps.taggerFinal.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

```
